name: build_docker

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
jobs:
  build_lint_test:
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    secrets: inherit
  docker_build:
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_docker_build.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
     image_name: 'staking-indexer'
