name: build_docker

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
jobs:
  push_docker:
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
     install-dependencies-command: 'sudo apt-get install libzmq3-dev'
  docker_build:
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_docker_build.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
     image_name: 'staking-indexer'
  docker_push:
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_docker_push.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
     image_name: 'staking-indexer'
