name: ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  dispatch_reusable_workflows:
    uses: ./.github/workflows/dispatch_reusable_workflows.yml
    with:
      reusable_go_lint_test: ${{ vars.REUSABLE_GO_LINT_TEST_FILE }}
      reusable_docker_pipeline: ${{ vars.REUSABLE_DOCKER_PIPELINE_URL }}
      publish: false
      dockerfile: ./contrib/images/staking-api-service/Dockerfile
