name: push_docker

on:
  push:
    branches:
    - '**'
    tags:
    - '**'
jobs:
  lint_test:
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@hiep/add-reusable-workflows
    with:
     install-dependencies-command: 'sudo apt-get install libzmq3-dev'
     run-unit-tests: true
     run-integration-tests: true
     run-lint: true

  docker_pipeline:
    needs: ["lint_test"]
    uses: hiepmai-babylonchain/.github/.github/workflows/reusable_docker_pipeline.yml@hiep/add-reusable-workflows
    secrets: inherit
    with:
     publish: false
