name: Sync Branch

on:
 workflow_dispatch:
   inputs:
    baseBranch:
      description: 'Base branch'
      required: true
      default: 'dev'
    targetBranch:
      description: 'Target branch'
      required: true
      default: 'main'
    reviewers:
      description: "Reviewer"
      type: string
      default: ""

jobs:
  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Sync from ${{ inputs.baseBranch }} to ${{ inputs.targetBranch }}'
          reviewers: ${{ inputs.reviewers }}
          base: ${{ inputs.baseBranch }}
          branch: ${{ inputs.targetBranch }}
          
        
