name: Sync Branches

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PAT }}
          base: dev
          branch: hiep/add-github-actions
          reviewers: hiepmai-babylonchain
          title: Automated PR from hiep/add-github-actions to dev

        
