name: Sync Branches

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
      - name: Opening pull request
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "hiep/add-github-actions"
          TO_BRANCH: "main"
          CONTENT_COMPARISON: true
